### ISSUE TITLE
Makefile fails if build dir does not exist

### ISSUE THREAD

**Issue by RobMa** [fruchti/leshy#1]
There is a minor issue in the makefiles. Building of the example codes in demo/ fails, if the build subdirectory does not exist.
```
$make all
cat: build/build-config.txt: Datei oder Verzeichnis nicht gefunden
/bin/sh: build/main.d.4326: Datei oder Verzeichnis nicht gefunden
makefile:67: build/main.d: Datei oder Verzeichnis nicht gefunden
make: *** [makefile:65: build/main.d] Fehler 1
```
As a workaround it works fine, if e.g. line 67 in demo/blink/makefile is commented out, but it may be needed for other purposes. 
`#include $(LOCAL_DEPENDS) `
Another workaround is of course to just create the build dir before invoking make...

**Comment by fruchti** [comment]
Thanks for contributing! The LOCAL_DEPENDS are indeed needed for correct incremental builds (so the right C files are recompiled after a change in a header). The problem was that the dependency files could not be created without the build directory. Now the build directory is created before the dependencies.
